doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    "DoctrineMigrations": "%kernel.project_dir%/migrations"
  enable_profiler: false
  # Ignorer les migrations manquantes
  all_or_nothing: false
  check_database_platform: false
  # Tolérer les migrations non enregistrées
  transactional: false
