# filepath: config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: true
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            allow_credentials: true
            max_age: 3600
